Fix fields in auth package not being trimmed automatically
podkrepi-bg/frontend pull request #1232
Opened 2022-12-06 19:27 UTC by Nnachevvv

When you enter email, firstName or lastName in one of the form in authorisation package and you accidentally put a leading/trailing space, it results into failed login because of invalid credentials. On most of the websites it's a common practice to ignore those "false" spaces when verifying the credentials, so we may apply it as well.

Closes https://github.com/podkrepi-bg/frontend/issues/1124

## Motivation and context

On most of the websites it's a common practice to ignore those "false" spaces when verifying the credentials, so we may apply it as well.

In order to fix that I had added trim to the end of the strings.

### Note
Unfortunately in the issue it was suggested that we should add trim in the yup validation chain to fix the problem. This didn't work and it seems that there is a incompatibility between Formik and Yup when there is a transformation. More information can be found here :
https://github.com/jaredpalmer/formik/issues/473
https://stackoverflow.com/questions/60423402/automatically-trim-white-spaces-with-yup-and-formik

## Screenshots:

<img width="1792" alt="Screenshot 2022-12-06 at 20 45 07" src="https://user-images.githubusercontent.com/44066540/206002008-9f5fa676-a72e-48e8-a595-a0d07433309c.png">

## Testing

### Steps to test

### Affected Forms

* LoginForm
* RegisterForm
* ForgottenPasswordForm
* UpdateNameModal
* UpdateEmailModal

2022-12-07 19:54 UTC, kachar requested changes
@Nnachevvv Usually we handle the trimming functionality as part of the input validation, so it can be reused and clear in terms of responsibility. 

I'd suggest that we undo the trim for individual fields and add `yup.string().trim()` method to the forms if not present.

If this trimming method doesn't work correctly let's investigate why.

https://github.com/podkrepi-bg/frontend/blob/196cab3b87931a1fc6e59f7733f48fc88522fcc3/src/common/form/validation.ts#L68-L71

For the locations that do not use the generic validators let's use them.

Check the docs at https://github.com/jquense/yup#stringtrimmessage-string--function-schema

2022-12-07 20:06 UTC, kachar commented
@Nnachevvv Oh that's so sad for Formik. Thanks for sharing this investigation.

One idea that comes to me is to use a custom transform method globally. 

```tsx
yup.string().transform((value, originalvalue) => value.trim())
// or even
yup.string().transform(trim)
```

Do you mind checking if this can help us solve the problem?

If it does then we can add a new helper for the transformation and use that instead of the standard `trim()`

2022-12-07 20:12 UTC, kachar commented
We can also add a custom method or override the `trim` method


```tsx
yup.addMethod(yup.string, 'trim', (value) => value.trim()) // override?
yup.addMethod(yup.string, 'realTrim', (value) => value.trim()) // custom method
```

2022-12-08 15:55 UTC, Nnachevvv commented
@kachar I have tested both ways to do this and they didn't work. 
Also I took a look again into the github issue reported for this problem. It seems that formik supports only validations, all transformation such as trim(), lowercase(), uppercase() will not work. I ran this code to test your ideas:
```js
function realTrim() {
  return this.transform(function (value) {
      return value.trim();
  });
}

Yup.addMethod(Yup.string, 'realTrim', realTrim);

const SignupForm = () => {
  return (
    <>
      <h1>Subscribe!</h1>
      <Formik
        initialValues={{
          firstName: "",
          lastName: "",
        }}
        validationSchema={Yup.object({
          firstName: Yup.string().transform((value, originalvalue) => value.trim()),
          lastName: Yup.string().realTrim()
        })}
        onSubmit={async (values, { setSubmitting }) => {
          console.log(values)
          await new Promise(r => setTimeout(r, 500));
          setSubmitting(false);
        }}
```
Full demo: https://codesandbox.io/s/formik-v2-tutorial-final-forked-gzbx48?file=/src/index.js

2022-12-08 19:40 UTC, kachar approved these changes
Thanks for providing a fix @Nnachevvv 

Indeed it's a bit sad that the transformation functions and auto trimming didn't work. We might revise that at some point, but now it's important to proceed forward.

2022-12-08 19:42 UTC, merged