Add donations filters for Admin Panel
podkrepi-bg/frontend pull request #1268
Opened 2022-12-28 17:59 UTC by AndreyGoranov

Now the admin can apply multiple filters at once and everything is done on the server
Had to do some small changes to the styles so everything appears normal including the overflow scroll of the data grid
I leveraged the mobx store to store the filters

Closes #1184
Relies on: https://github.com/podkrepi-bg/api/pull/409

**Note:** I noticed on some of the other grids of the admin panel we don't have a scroll and can't view all the data displayed in the table

## Motivation and context

## Screenshots:

![image](https://user-images.githubusercontent.com/55912299/209852556-3016f3b2-b808-4af7-9fb9-d33eebdcd789.png)

## Testing

### Steps to test

### Affected urls

## Environment

### New environment variables:

- [ ] `NEW_ENV_VAR`: env var details

### New or updated dependencies:

Dependency name|Previous version|Updated version|Details
---|---|---|---
`dependency/name`|`v1.0.0`|`v2.0.0`|

2022-12-29 12:46 UTC, ani-kalpachka approved these changes

2023-01-03 15:44 UTC, igoychev requested changes
Great improvement!
Just please fix the build as you may saw already it fails with:

`./src/pages/admin/donations/index.tsx:7:53
Type error: Argument of type 'number' is not assignable to parameter of type '{ pageIndex: number; pageSize: number; }'.`

2023-01-06 08:40 UTC, igoychev approved these changes

2023-01-06 09:45 UTC, igoychev approved these changes

2023-01-06 10:17 UTC, merged