Change formula to calculate Stripe's fee
podkrepi-bg/frontend pull request #1360
Opened 2023-02-20 15:05 UTC by sashko9807

Closes #1358 

## Motivation and context
This PR closes the above mentioned issue, which results to a better user experience.

## Testing

### Steps to test
1. Switch between wanting to cover and not wanting to cover the fee. Stripe's fee should be the same.

### Affected urls
campaigns/donation/{slug}

2023-02-20 20:22 UTC, dimitur2204 approved these changes
This is how we should do it probably. Just make sure the formula in `stripeIncludeFeeCalculator{region}` is the right one

2023-02-21 08:07 UTC, igoychev requested changes
The change looks logic, however have you ensured that it returns the same amount?

2023-02-21 08:13 UTC, dimitur2204 commented
Could you please add jest tests for these functions consiedring they are quite crucial @sashko9807?

2023-02-21 11:36 UTC, sashko9807 commented
@igoychev 
Manually checked the amount, against cards issued in all supported regions. Stripe's fee is the exact same,  with the one shown in the deployed branch, whenever "I want to cover the fee" checkbox is checked.

@dimitur2204 
Please check if those simple unit test will suffice. Also if they are in the correct directory.

2023-02-21 12:37 UTC, igoychev commented
> Manually checked the amount, against cards issued in all supported regions. Stripe's fee is the exact same, with the one shown in the deployed branch, whenever "I want to cover the fee" checkbox is checked.

The assumption that the fees should be equal is not correct.

When you base your calculations, have in mind the following:
1/ The fees are always calculated on the total charged amount.
2/ When the user selects to pay the fee AND to ensure X amount of money is donated to campaign, this makes the charged amount bigger, hence the fee is also different.

This is the same logic if you want to calculate VAT(ДДС) taxes - try this for example: https://www.scoosh.com/vat-calculator/ and see how the VAT is different when included or not included.

And finally - these calculations were tested with Stripe and Stripe calculates the same fees on the transaction.

2023-02-21 13:07 UTC, sashko9807 commented
> When you base your calculations, have in mind the following: 
>1. The fees are always calculated on the total charged amount. 
>2. When the user selects to pay the fee AND to ensure X amount of money is donated to campaign, this makes the charged amount bigger, hence the fee is also different.

> This is the same logic if you want to calculate VAT(ДДС) taxes - try this for example: https://www.scoosh.com/vat-calculator/ and see how the VAT is different when included or not included.
> 
> And finally - these calculations were tested with Stripe and Stripe calculates the same fees on the transaction.

My mistake. Completely missed out that since the total charged amount is bigger, so should be the fee. This revelation makes this change completely incorrect. 

As no changes are actually required to the currently used formula(without introducing unnecessary complexity), should I close the PR, or rebase with just the unit tests in(assuming they are fine)?

2023-02-21 13:12 UTC, dimitur2204 commented
> > When you base your calculations, have in mind the following:
> > 
> > 1. The fees are always calculated on the total charged amount.
> > 2. When the user selects to pay the fee AND to ensure X amount of money is donated to campaign, this makes the charged amount bigger, hence the fee is also different.
> 
> > This is the same logic if you want to calculate VAT(ДДС) taxes - try this for example: https://www.scoosh.com/vat-calculator/ and see how the VAT is different when included or not included.
> > And finally - these calculations were tested with Stripe and Stripe calculates the same fees on the transaction.
> 
> My mistake. Completely missed out that since the total charged amount is bigger, so should be the fee. This revelation makes this change completely incorrect.
> 
> As no changes are actually required to the currently used formula(without introducing unnecessary complexity), should I close the PR, or rebase with just the unit tests in(assuming they are fine)?

Adjust the tests to the logic as explained and we will roll them out.

2023-02-21 16:43 UTC, dimitur2204 approved these changes

2023-02-21 16:55 UTC, dimitur2204 requested changes
You somehow seem to have commited without having ran the formatting. It should run by itself, but you can run it manually using `yarn run lint && yarn run format`

2023-02-22 06:34 UTC, igoychev approved these changes

2023-02-22 08:44 UTC, dimitur2204 approved these changes

2023-02-22 08:44 UTC, merged