rough version of fixing issue with  descriptions
podkrepi-bg/frontend pull request #1427
Opened 2023-05-04 18:16 UTC by dzhaniivanov

https://github.com/podkrepi-bg/frontend/issues/1420

## Motivation and context

first version if u think its okey i will separate the logic  in component

i test it with big dummy text and i think its looks good on desktop and on mobile.
i am open to any suggestions :)

2023-05-06 07:01 UTC, slavcho requested changes
Great!
Test it on my machine - it works well:

![image](https://user-images.githubusercontent.com/99622/236608668-eb1a5e5a-754e-4ff4-82e4-27e863d2f106.png)


Just fix the minor comments and push.

2023-05-06 07:03 UTC, slavcho commented on src/components/client/campaigns/CampaignPublicExpensesGrid.tsx
> +              {params?.value.slice(0, 10)}...
And remove the ... postfix

2023-05-06 09:12 UTC, sashko9807 commented
MUI Datagrid also supports variable row height based on the content [link to docs](https://mui.com/x/react-data-grid/row-height/#dynamic-row-height). This way the longer text descriptions should be visible, without any trim or ellipsis applied.

Note: I am just mentioning an alternative way to solve this issue. This is not a review

2023-05-06 11:46 UTC, slavcho commented
> MUI Datagrid also supports variable row height based on the content [link to docs](https://mui.com/x/react-data-grid/row-height/#dynamic-row-height). This way the longer expense description should be visible, without any trim or ellipsis applied.
> 
> Note: I am just mentioning an alternative way to solve this issue. This is not a review

This is actually very good!
Lets do this - just tested it - works:

![image](https://user-images.githubusercontent.com/99622/236622033-28140ff6-b5e2-475a-af56-b3ee1f776106.png)

Dzhani - just add getRowHeight={() => 'auto'} - and remove the rest :)

2023-05-07 10:38 UTC, sashko9807 commented
> > MUI Datagrid also supports variable row height based on the content [link to docs](https://mui.com/x/react-data-grid/row-height/#dynamic-row-height). This way the longer expense description should be visible, without any trim or ellipsis applied.
> > Note: I am just mentioning an alternative way to solve this issue. This is not a review
> 
> This is actually very good! Lets do this - just tested it - it works:
> 
> 
> Dzhani - simply add getRowHeight={() => 'auto'} - and remove the rest :)

Consider adding min width to either the whole table or the description column, otherwise the text could still be clipped on smaller viewports(<600px), due to the smaller column width.

Another thing looking at the screenshot above,  maybe we should align the attachment files on a single row, rather than  column(if possible).

2023-05-10 05:40 UTC, dzhaniivanov commented
for some reason getRowHeight doesn't work as we expected on my machine

2023-05-11 06:18 UTC, dzhaniivanov commented
i changed the popover with auto getRowHeight prop but on my machine (test with chrome and firefox) it doesn't work as expected in the MUI docs. I (and Sashko) researched the possible problem and cleared the cache files, node_modules, re-cloned the repo but nothing worked. Slavcho, if you have any suggestion, please ping  me in discord maybe :)

2023-05-22 06:20 UTC, igoychev approved these changes

2023-05-22 10:02 UTC, merged