removed legacy objectFit property from next/image component
podkrepi-bg/frontend pull request #1534
Opened 2023-08-01 12:38 UTC by Nkiriobasi

Closes #{issue number}

## Motivation and context

## Screenshots:

Before|After
---|---
Paste screenshot|Paste screenshot

## Testing

### Steps to test

### Affected urls

## Environment

### New environment variables:

- [ ] `NEW_ENV_VAR`: env var details

### New or updated dependencies:

Dependency name|Previous version|Updated version|Details
---|---|---|---
`dependency/name`|`v1.0.0`|`v2.0.0`|

2023-08-02 08:16 UTC, sashko9807 requested changes
Please keep in mind that, objectFit is a valid CSS property. What the warning from issue #1529 refers to is move the objectFit, inside the style of the image component, rather than it being a prop.

So if  we have `<Image ..... objectFit='contain'/>`
We need to move objectFit into style prop e.g.
`<Image style={{objectFit: 'contain}} />`

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/about/AboutPage.styled.tsx
> -  objectFit: 'cover',
Should be reverted.

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/blog/FeaturedImage.tsx
> +  // objectFit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down'
Should be reverted

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/blog/FeaturedImage.tsx
> +          style={{ objectPosition: defaultImage.objectPosition }}
Should be reverted

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/campaigns/CampaignSlider.tsx
> +          <Image src={sliderImages[0]} alt="campaign" height={300} width={400} />
This is ok

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/campaigns/CampaignSlider.tsx
> +            <Image src={image} alt="campaign" height={300} width={400} />
Move `objectFit='cover'` inside the style prop

2023-08-02 08:16 UTC, sashko9807 commented on src/components/client/index/sections/TeamMembersSection/TeamMembersSection.tsx
> +          style={{ maxWidth: '100%', height: 'auto' }}
Should be reverted.

2023-08-02 10:44 UTC, Nkiriobasi commented
Alright, no problem

2023-08-02 10:46 UTC, ani-kalpachka commented
@Nkiriobasi thanks for the contribution!
I think we should keep the objectFit: 'cover' because without it the styles do not look appropriate.

2023-08-06 15:36 UTC, igoychev approved these changes
thanks for the help!

2023-08-07 04:43 UTC, ani-kalpachka approved these changes

2023-08-07 06:10 UTC, merged