New design notifications news
podkrepi-bg/frontend pull request #1673
Opened 2023-11-24 12:21 UTC by RalitsaIlieva

Closes #1550 (news subscription)

## Motivation and context

There is new design that should be implemented.

## Screenshots:

![image](https://github.com/podkrepi-bg/frontend/assets/17964436/08fa58a4-9ea1-4583-ac17-f8038dcb0029)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/3cf1e163-7d1a-4ec7-89e1-306703150393)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/bbc61208-0ba3-49ce-8f90-0865175203e2)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/9b1d52e6-f9ed-46d1-a998-c9a5f33fb102)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/09bf95fe-a84e-4615-b8ae-12c1de00e621)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/97b318e6-e0b5-44ed-a472-63d8c786a95b)
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/e16a6353-59c5-4ef8-b585-18046b8fcbd3)

Before|After
---|---
Paste screenshot|Paste screenshot

## Testing

### Steps to test

### Affected urls

## Environment

### New environment variables:

- [ ] `NEW_ENV_VAR`: env var details

### New or updated dependencies:

Dependency name|Previous version|Updated version|Details
---|---|---|---
`dependency/name`|`v1.0.0`|`v2.0.0`|

2023-11-28 16:51 UTC, ani-kalpachka approved these changes

2023-12-16 12:06 UTC, sashko9807 requested changes

2023-12-16 16:11 UTC, RalitsaIlieva commented on src/components/common/form/CheckboxField.tsx
> +  sx?: object
done

2023-12-16 16:11 UTC, RalitsaIlieva commented on src/components/client/campaigns/CampaignDetails.tsx
> +        {expensesList?.length ||
fixed

2023-12-16 23:55 UTC, swolf86 commented on src/components/client/index/IndexPage.tsx
> +      <SubscriptionSection />
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?type=design&node-id=3904%3A13406&mode=design&t=i8Eql4jYENDpTGgA-1

1. under what have we achieved?
Съществуващата секция “Какво постигнахме досега” да се допълни с функционалност за абониране
2. under Who is behind Podkrepi.bg?

2023-12-17 08:25 UTC, RalitsaIlieva commented on src/components/client/index/IndexPage.tsx
> +      <SubscriptionSection />
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/5b48d335-2bf1-4a37-8442-fce42d9558be)

2023-12-17 08:27 UTC, RalitsaIlieva commented on src/components/client/index/IndexPage.tsx
> +      <SubscriptionSection />
![image](https://github.com/podkrepi-bg/frontend/assets/17964436/4d3ac1eb-4798-4eb1-93a4-31a77e82e40f)

2023-12-17 08:29 UTC, RalitsaIlieva commented on src/components/client/index/IndexPage.tsx
> +      <SubscriptionSection />
There are 4 positions of the Subscribe for news according to the design in Figma. If something changed, please, update it on time

2023-12-29 15:24 UTC, ani-kalpachka commented
@sashko9807 The comments seem to be fixed. Could you please check and confirm?

2024-01-03 16:19 UTC, sashko9807 approved these changes
Approving this in order to not block functionality tests in staging environment .  Though the commit still needs some polishing before deploying to production.

2024-01-03 20:11 UTC, merged