translations refinements
podkrepi-bg/frontend pull request #1727
Opened 2024-03-01 12:51 UTC by dzhaniivanov

#1724  + translation bugs caught on the fly from the team.

![task](https://github.com/podkrepi-bg/frontend/assets/68897146/0b742f77-f26c-49cc-9b34-67a65cc056af)

2024-03-02 04:23 UTC, ani-kalpachka commented on public/locales/bg/one-time-donation.json
> +    "card-include-fees": "Съгласен съм да покрия таксата за превода, така че да се получи чистата вума, която съм избрал/а като дарение, за карта издадена в: ",
Did you mean 'чистата сума'?

2024-03-02 04:26 UTC, ani-kalpachka commented on public/locales/bg/one-time-donation.json
> +    "recurring-donation-info": "Желая да дарявам същата сума всеки месец до края на кампанията.Може да се откажете по всяко време в профила си: "
Can we keep the space between these two setences please?

2024-03-02 04:26 UTC, dzhaniivanov commented on public/locales/bg/one-time-donation.json
> +    "card-include-fees": "Съгласен съм да покрия таксата за превода, така че да се получи чистата вума, която съм избрал/а като дарение, за карта издадена в: ",
Yup, copy/paste ☺️ sorry

2024-03-02 04:28 UTC, ani-kalpachka requested changes
Good improvements!
Can you please check the minor issues related to the translations?

2024-03-06 05:15 UTC, ani-kalpachka approved these changes

2024-03-06 10:53 UTC, merged