add help us improve field to all registrations
podkrepi-bg/frontend pull request #1737
Opened 2024-03-14 10:02 UTC by kdachev97

Added a new tick box in Registration Forms for both EN and BG.

Before:
<img width="701" alt="Screenshot 2024-03-13 at 10 51 05" src="https://github.com/podkrepi-bg/frontend/assets/149360576/3f732d9a-58d7-40e4-aa1e-3baf6496d310">
<img width="717" alt="Screenshot 2024-03-13 at 10 50 58" src="https://github.com/podkrepi-bg/frontend/assets/149360576/5be95b75-4efe-4d3e-a929-841a91b385d5">

After:
<img width="691" alt="Screenshot 2024-03-13 at 10 49 01" src="https://github.com/podkrepi-bg/frontend/assets/149360576/8a4df9f3-b884-40be-b6b2-468aa7c3356b">
<img width="667" alt="Screenshot 2024-03-13 at 10 49 57" src="https://github.com/podkrepi-bg/frontend/assets/149360576/0cb8b92e-7f70-4828-ac18-4d86d0aea3a1">

2024-03-15 11:36 UTC, sashko9807 requested changes
Well done. There are minor last-minute  changes to the text, mentioned below, please look at them.

This commit should also be supplemented, by changes in the backend as well, in order to keep track of who actually has agreed to help, so if you can please do.

Needed changes to the backend are:
 [Adding helpUsImprove field](https://github.com/podkrepi-bg/api/blob/master/schema.prisma#L33), to the prisma model

- Adding helpUsImprove property, to the [registerDto](https://github.com/podkrepi-bg/api/blob/master/apps/api/src/auth/dto/register.dto.ts#L53) 

If you have any further questions, regarding the requested changes feel free to contact me anytime.

Thank you for your contribution!

2024-03-15 11:36 UTC, sashko9807 commented on public/locales/bg/validation.json
> +  "help-us-improve": "Искате ли да ни помогнете да подобрим платформата? Искаме да чуем вашето мнение? Отделете ни 30 мин за подобрите платформа на подкрепи.бг"
It was discussed with the design team, it is better to replace `30 мин` with `30 минути`. 
Same goes for the EN translation, `30 mins to `30 `minutes`

2024-03-15 11:36 UTC, sashko9807 commented on src/components/common/form/HelpUsImproveField.tsx
> +          {/* <ExternalLink href={routes.helpUsImprove}>
Please remove the commented line.

2024-03-17 09:13 UTC, ani-kalpachka commented on public/locales/bg/validation.json
> +  "help-us-improve": "Искате ли да ни помогнете да подобрим платформата? Искаме да чуем вашето мнение? Отделете ни 30 мин за подобрите платформа на подкрепи.бг"
I would update it to:
"Искате ли да ни помогнете да подобрим платформата? Искаме да чуем Вашето мнение? Отделете ни 30 минути, за подобрите платформа на Подкрепи.бг""

2024-03-17 18:49 UTC, ani-kalpachka approved these changes

2024-03-18 17:47 UTC, sashko9807 approved these changes

2024-03-18 17:54 UTC, sashko9807 requested changes
The automatic linter appears, to have failed. Do you mind running `yarn lint`(on the frontend repo), and commit the changes?

2024-03-19 10:42 UTC, merged

2024-03-28 11:35 UTC, wqweto commented on public/locales/bg/validation.json
> +  "help-us-improve": "Искате ли да ни помогнете да подобрим платформата? Искаме да чуем вашето мнение? Отделете ни 30 мин за подобрите платформа на подкрепи.бг"
"Искаме да чуем вашето мнение" and "We want to hear from you" are plain statements and don't need question mark unless the original intend was to read "**Искате** да чуем вашето мнение?" and "**You** want us to hear from you?"

2024-03-28 11:44 UTC, kdachev97 commented on public/locales/bg/validation.json
> +  "help-us-improve": "Искате ли да ни помогнете да подобрим платформата? Искаме да чуем вашето мнение? Отделете ни 30 мин за подобрите платформа на подкрепи.бг"
@wqweto Този текст е вече променен в друг тикет: https://github.com/podkrepi-bg/frontend/pull/1751/commits/dbfc1483a55d467399012de75d344f08d3fe665b