feat: create a campaign application stepper skeleton (Epic #1842)
podkrepi-bg/frontend pull request #1859
Opened 2024-06-18 21:56 UTC by teodorazhelyazkova

Create a campaign application stepper skeleton connected to [Epic #1842](https://github.com/podkrepi-bg/frontend/issues/1842)
I have used for reference the `src/components/client/irregularit/helpers/IrregularityForm.tsx`

## Screenshots:

![Capture](https://github.com/podkrepi-bg/frontend/assets/103574320/59b35f87-6fe8-4f66-bfe1-9183cc0a6f63)

## Testing

### Steps to test

1. Login as normal user
2. Visit `http://localhost:3040/campaigns/application`
3. Click buttons for changing of active step functionality

2024-06-19 11:58 UTC, sashko9807 requested changes

2024-06-19 11:58 UTC, sashko9807 commented on src/components/client/campaign-application/helpers/campaignApplication.types.ts
> +export type CampaignApplicationFormData = {}
Linter errors on this. 
Change the CampaignApplicationFormData type temporary to `Record<string,string>` until the FormData body is figured out.

2024-06-20 14:57 UTC, sashko9807 commented on src/components/client/campaign-application/helpers/campaignApplication.types.ts
> +export type CampaignApplicationFormData = {}
No worries. This is what the CI/CD  is for.

2024-06-20 14:57 UTC, sashko9807 approved these changes

2024-06-21 06:47 UTC, gparlakov reviewed
LGTM

2024-06-21 07:33 UTC, merged