Update gdpr hyperlink on FAQ
podkrepi-bg/frontend pull request #1923
Opened 2024-09-09 20:38 UTC by ani-kalpachka

2024-09-13 07:14 UTC, sashko9807 requested changes

2024-09-13 07:14 UTC, sashko9807 commented on src/components/client/faq/contents/donation.tsx
> +            'https://cpdp.bg/%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD-%D0%B7%D0%B0-%D0%B7%D0%B0%D1%89%D0%B8%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BB%D0%B8%D1%87%D0%BD%D0%B8%D1%82%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D0%B8/'
Lets have it without the URL encoding
`https://cpdp.bg/закон-за-защита-на-личните-данни` should work just as good, but it is more readable

2024-09-13 07:24 UTC, ani-kalpachka commented on src/components/client/faq/contents/donation.tsx
> +            'https://cpdp.bg/%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD-%D0%B7%D0%B0-%D0%B7%D0%B0%D1%89%D0%B8%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BB%D0%B8%D1%87%D0%BD%D0%B8%D1%82%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D0%B8/'
I agree. This was my first aproach. However this did not work when I used this url in the code. It cuts the cyrillic text and redirects to the home page again. Might be an encoding issue. Can you suggest a solution?

2024-09-30 13:01 UTC, sashko9807 approved these changes

2024-09-30 16:11 UTC, merged